#! /bin/sh
$HOME/.config/screenlayout/display.sh
pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &
nitrogen --restore &
picom -b --experimental-backends &
xrdb ~/.Xresources &
#$HOME/.config/.fehbg &
$HOME/.config/polybar/launch.sh &
#$HOME/.config/.hdmi.sh &
nm-applet &

###---MONITORS---###
bspc monitor eDP1 -d I II III IV V VI VII
bspc monitor HDMI1 -d I II III

###---GLOBAL SETTINGS---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#676E95"
bspc config active_border_color   "#C792EA"
bspc config focused_border_color  "#C792EA"
bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc config border_width         3
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a telegram-desktop desktop='^2' border=off
bspc rule -a TelegramDesktop desktop='^2'

bspc rule -a firefox state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
